signatures:
  - image: ghcr.io/goreleaser/*
    github_actions:
      owner: goreleaser
      # repo: a-repo # optional
  - image: ghcr.io/kubewarden/*
    github_actions:
      owner: kubewarden
modifyImagesWithDigest: false
