---
apiVersion: v1
kind: Pod
metadata:
  name: goreleaser
spec:
  containers:
  - image: ghcr.io/goreleaser/goreleaser
    imagePullPolicy: Always
    name: goreleaser
    command:
      - goreleaser
      - --version
