---
apiVersion: v1
kind: Pod
metadata:
  name: goreleaser-v1
spec:
  containers:
  - image: ghcr.io/goreleaser/goreleaser:v0.175.0
    imagePullPolicy: Always
    name: goreleaser
    command:
      - goreleaser
      - --version
