---
apiVersion: v1
kind: Pod
metadata:
  name: goreleaser
spec:
  containers:
  - image: ghcr.io/goreleaser/goreleaser:v1.10.2
    imagePullPolicy: Always
    name: goreleaser
    command:
      - goreleaser
      - --version
